#!/bin/bash
impi_version=`ls /opt/intel/impi`
source /opt/intel/impi/${impi_version}/bin64/mpivars.sh
export MPI_ROOT=$I_MPI_ROOT
source /data/apps/OpenFOAM/OpenFOAM-4.x/etc/bashrc

export MPI_ARGS='-genv I_MPI_FABRICS shm:dapl -genv I_MPI_DAPL_PROVIDER ofa-v2-ib0 -genv I_MPI_DYNAMIC_CONNECTION 0 -genv I_MPI_FALLBACK_DEVICE 0 -genv I_MPI_DAPL_TRANSLATION_CACHE 0'

# nodes and ppn are provided in param
$jobdir/$runner $nodes $ppn

